CourseWork/Models/Crime.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CourseWork.Models {
    public class Crime {
        [Key] public int Id { get; set;}
        [Required] public DateTime Date { get; set;}
        public string Name { get; set; }
        public string Punishment { get; set; }
        public ICollection<CrimeCriminal> Members { get; set; } = new List<CrimeCriminal>();
    }
}

CourseWork/Models/CrimeViewModel.cs
namespace CourseWork.Models
{
    public class CrimeViewModel
    {
        public Crime Crime { get; set; }
        public bool IsSelected { get; set; }
    }
}

CourseWork/Controllers/CrimesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseWork.Models;
using CourseWork.Data;

namespace CourseWork.Controllers
{
    public class CrimesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CrimesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Crimes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Crime.ToListAsync());
        }

        // GET: Crimes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crime = await _context.Crime
                .FirstOrDefaultAsync(m => m.Id == id);
            if (crime == null)
            {
                return NotFound();
            }

            return View(crime);
        }

        // GET: Crimes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Crimes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,Name,Punishment")] Crime crime)
        {
            if (ModelState.IsValid)
            {
                _context.Add(crime);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(crime);
        }

        // GET: Crimes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crime = await _context.Crime.FindAsync(id);
            if (crime == null)
            {
                return NotFound();
            }
            return View(crime);
        }

        // POST: Crimes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Name,Punishment")] Crime crime)
        {
            if (id != crime.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(crime);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CrimeExists(crime.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(crime);
        }

        // GET: Crimes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crime = await _context.Crime
                .FirstOrDefaultAsync(m => m.Id == id);
            if (crime == null)
            {
                return NotFound();
            }

            return View(crime);
        }

        // POST: Crimes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var crime = await _context.Crime.FindAsync(id);
            _context.Crime.Remove(crime);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CrimeExists(int id)
        {
            return _context.Crime.Any(e => e.Id == id);
        }
    }
}

CourseWork/Views/Crimes/Create.cshtml
@model CourseWork.Models.Crime

@{
    ViewData["Title"] = "Create";
}

<h1>Создать преступление</h1>

<h4>Преступление</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            
            <div class="form-group">
                <label asp-for="Date" class="control-label">Дата время</label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Punishment" class="control-label">Наказание</label>
                <input asp-for="Punishment" class="form-control" type="text" />
                <span asp-validation-for="Punishment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" /> | 
                <a class="btn btn-danger" asp-controller="Crimes" asp-action="Index">Вернуться</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseWork/Views/Crimes/Delete.cshtml
@model CourseWork.Models.Crime

@{
    ViewData["Title"] = "Delete";
}

<h1>Удалить преступление</h1>

<h3>Вы уверены что хотите удалить перступление?</h3>
<div>
    
    <hr />
    <dl class="row">
    <dt class = "col-sm-2">
                ID
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Id)
            </dd>
        <dt class = "col-sm-2">
            Дата-время
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            Название
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Наказание
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Punishment)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a class="btn btn-danger" asp-action="Index">Вернуться</a>
    </form>
</div>

CourseWork/Views/Crimes/Details.cshtml
@model CourseWork.Models.Crime

@{
    ViewData["Title"] = "Details";
}

<h1>Детали</h1>

<div>
    <h4>Преступление</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
                    ID
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Id)
                </dd>
            <dt class = "col-sm-2">
                Дата-время
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt class = "col-sm-2">
                Название
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class = "col-sm-2">
                Наказание
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Punishment)
            </dd>
        </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Редактировать</a> |
    <a asp-action="Index" class="btn btn-primary">Вернуться</a>
</div>

CourseWork/Views/Crimes/Edit.cshtml
@model CourseWork.Models.Crime

@{
    ViewData["Title"] = "Edit";
}

<h1>Редактировать преступление</h1>

<h4>Преступление</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Date" class="control-label">Дата-время</label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Punishment" class="control-label">Наказание</label>
                <input asp-for="Punishment" class="form-control" />
                <span asp-validation-for="Punishment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" /> | 
                <a class="btn btn-danger" asp-action="Index">Вернуться</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseWork/Views/Crimes/Index.cshtml
@model IEnumerable<CourseWork.Models.Crime>

@{
    ViewData["Title"] = "Index";
}

<h1>Преступления</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Создать преступление</a>
    
</p>
<form method="post">
<table class="table">
    <thead>
    <tr>
        <th> ID</th>
        <th>
            Дата-Время
        </th>
        <th>
            Название
        </th>
        <th>
            Наказание
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Punishment)
            </td>
            <td>
                <a class="btn btn-primary text-white col-8" asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> 
                <a class="btn btn-info text-white col-8" asp-action="Details" asp-route-id="@item.Id">Детали</a> 
                <a class="btn btn-danger text-white col-8" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>
</form>