CourseWork/Models/AddCrimeViewModel.cs
using System.Collections.Generic;

namespace CourseWork.Models
{
    public class AddCrimeViewModel
    {
        public IEnumerable<CrimeViewModel> Crimes { get; set; }

        public int CriminalId { get; set; }
    }
}

CourseWork/Models/AddOrganisationViewModel.cs
using System.Collections.Generic;

namespace CourseWork.Models
{
    public class AddOrganisationViewModel
    {
        public IEnumerable<OrganisationViewModel> Organisations { get; set; }

        public int CriminalId { get; set; }
    }
}

CourseWork/Models/Criminal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CourseWork.Models {
    public class Criminal {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public byte Age { get; set; }
        public double Height { get; set; }
        public DateTime BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string Sex { get; set; }
        public string HairColor { get; set; }
        public string EyeColor { get; set; }
        public string ExtraSigns { get; set; }
        public string LastAccomodation { get; set; }
        public ICollection<CriminalOrganisation> Organisations { get; set; } = new List<CriminalOrganisation>();
        public ICollection<CrimeCriminal> Crimes { get; set; } = new List<CrimeCriminal>();
        public string CrimesAsString { get; set;}
        public string OrganisationsAsString { get; set; }
        public bool IsArchived { get; set; }
    }
}

CourseWork/Controllers/CriminalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseWork.Models;
using CourseWork.Data;

namespace CourseWork.Controllers
{
    public class CriminalsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CriminalsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> AddOrganisation(int criminal_id)
        {
            var organisations = await _context.Organisation.Include(c => c.Members).ToListAsync();
            var viewModels =
                organisations.Select(item => new OrganisationViewModel()
                {
                    Organisation = item,
                    IsSelected = item.Members.Any(item => item.CriminalId == criminal_id)
                }).ToList();

            return View(new AddOrganisationViewModel() { Organisations = viewModels, CriminalId = criminal_id });
        }
        public async Task<IActionResult> OrgChangeStatus(int org_id, int criminal_id, bool status)
        {
            var criminal = _context.Criminal.Include(c => c.Organisations).FirstOrDefault(item => item.Id == criminal_id);
            if (criminal != null)
            {
                if (status)
                {
                    var organisation = new CriminalOrganisation() { OrganisationId = org_id, CriminalId = criminal_id };
                    criminal.Organisations.Add(organisation);
                    criminal.OrganisationsAsString += $"{organisation.OrganisationId}, ";
                }
                else
                {
                    criminal.Organisations.Remove(criminal.Organisations.FirstOrDefault(item => item.OrganisationId == org_id));
                    criminal.OrganisationsAsString = criminal.OrganisationsAsString.Replace($"{org_id}, ", "");

                }
                await _context.SaveChangesAsync();
                return RedirectToAction("AddOrganisation", new { criminal_id = criminal_id });
            }

            return NotFound();

        }
        public async Task<IActionResult> AddCrime(int criminal_id)
        {
            var crimes = await _context.Crime.Include(c => c.Members).ToListAsync();
            var viewModels = 
                crimes.Select(item => new CrimeViewModel()
                {
                    Crime = item, 
                    IsSelected = item.Members.Any(item => item.CriminalId == criminal_id)
                }).ToList();

            return View(new AddCrimeViewModel() {Crimes = viewModels, CriminalId = criminal_id });
        }

        public async Task<IActionResult> ChangeStatus(int crime_id, int criminal_id, bool status)
        {
            var criminal = _context.Criminal.Include(c => c.Crimes).FirstOrDefault(item => item.Id == criminal_id);
            if (criminal != null)
            {
                if (status)
                {
                    var crime = new CrimeCriminal() {CrimeId = crime_id, CriminalId = criminal_id};
                    criminal.Crimes.Add(crime);
                    criminal.CrimesAsString += $"{crime.CrimeId}, ";
                }
                else
                {
                    criminal.Crimes.Remove(criminal.Crimes.FirstOrDefault(item => item.CrimeId == crime_id));
                    criminal.CrimesAsString = criminal.CrimesAsString.Replace($"{crime_id}, ", "");
                    
                }
                await _context.SaveChangesAsync(); 
                return RedirectToAction("AddCrime", new { criminal_id = criminal_id });
            }

            return NotFound();

        }
        // GET: Criminals
        public async Task<IActionResult> Index(string searchString)
        {
            
            var criminal = from s in _context.Criminal
                   select s;
             if (!String.IsNullOrEmpty(searchString))
            {
                var sS = searchString.Split(' ');
                foreach (var parameter in sS)
                {
                    criminal = criminal.Where(s => s.LastName.Contains(parameter)
                                        || s.FirstName.Contains(parameter)
                                        || s.NickName.Contains(parameter)
                                        || s.ExtraSigns.Contains(parameter)
                                        || s.HairColor.Contains(parameter)
                                        || s.EyeColor.Contains(parameter)
                                        || s.Age.ToString().Contains(parameter)
                                        || s.Height.ToString().Contains(parameter)
                                        || s.Sex.Contains(parameter));
                }
            }
                return View(await criminal.ToListAsync());
        }
        public async Task<IActionResult> Archived(string searchString)
        {

            var criminal = from s in _context.Criminal
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                var sS = searchString.Split(' ');
                foreach (var parameter in sS)
                {
                    criminal = criminal.Where(s => s.LastName.Contains(parameter)
                                        || s.FirstName.Contains(parameter)
                                        || s.NickName.Contains(parameter)
                                        || s.ExtraSigns.Contains(parameter)
                                        || s.HairColor.Contains(parameter)
                                        || s.EyeColor.Contains(parameter)
                                        || s.Age.ToString().Contains(parameter)
                                        || s.Height.ToString().Contains(parameter)
                                        || s.Sex.Contains(parameter));
                }
            }
            return View(await criminal.ToListAsync());
        }
        // GET: Criminals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var criminal = await _context.Criminal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (criminal == null)
            {
                return NotFound();
            }

            return View(criminal);
        }

        // GET: Criminals/Create
        public IActionResult Create()
        {
            return View();
        }
        // POST: Criminals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,NickName,Age,Height,BirthDate,BirthPlace,Sex,HairColor,EyeColor,ExtraSigns,LastAccomodation")] Criminal criminal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(criminal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(criminal);
        }
        
        // GET: Criminals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var criminal = await _context.Criminal.FindAsync(id);
            if (criminal == null)
            {
                return NotFound();
            }
            return View(criminal);
        }

        // POST: Criminals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,NickName,Age,Height,BirthDate,BirthPlace,Sex,HairColor,EyeColor,ExtraSigns,LastAccomodation")] Criminal criminal)
        {
            if (id != criminal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(criminal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CriminalExists(criminal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(criminal);
        }

        // GET: Criminals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var criminal = await _context.Criminal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (criminal == null)
            {
                return NotFound();
            }

            return View(criminal);
        }

        // POST: Criminals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var criminal = await _context.Criminal.FindAsync(id);
            _context.Criminal.Remove(criminal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Archive(int? id)
        {

CourseWork/Views/Criminals/AddCrime.cshtml
@model CourseWork.Models.AddCrimeViewModel

@{
    ViewData["Title"] = "Add Crime";
}

<h1>Добавить преступление</h1>

<p>
    <a asp-controller="Criminals" asp-action="Index" class="btn btn-primary">Вернуться</a>
</p>
    <table class="table">
        <thead>
            <tr>
                <th>Выбрать</th>
                <th>Статья</th>
                <th>
                    Дата-Время
                </th>
                <th>
                    Преступление
                </th>
                <th>
                    Наказание
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.Crimes)
            {
                <tr>
                    <td>
                        <a class="btn btn-success text-white " asp-action="ChangeStatus" asp-route-crime_id="@item.Crime.Id" asp-route-criminal_id="@Model.CriminalId"  asp-route-status="@(!item.IsSelected)">@(item.IsSelected ? "-" : "+")</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem=>item.Crime.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Crime.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Crime.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Crime.Punishment)
                    </td>
                </tr>
            }
        </tbody>
    </table>

CourseWork/Views/Criminals/AddOrganisation.cshtml
@model CourseWork.Models.AddOrganisationViewModel

@{
    ViewData["Title"] = "Add Crime";
}

<h1>Добавить организацию</h1>

<p>
    <a asp-controller="Criminals" asp-action="Index" class="btn btn-primary">Вернуться</a>
</p>
    <table class="table">
        <thead>
            <tr>
                <th>Выбрать</th>
                <th>ID</th>
                <th>
                    Название
                </th>
                <th>
                    Босс
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.Organisations)
            {
                <tr>
                    <td>
                        <a class="btn btn-success text-white " asp-action="OrgChangeStatus" asp-route-org_id="@item.Organisation.Id" asp-route-criminal_id="@Model.CriminalId"  asp-route-status="@(!item.IsSelected)">@(item.IsSelected ? "-" : "+")</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem=>item.Organisation.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Organisation.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Organisation.Boss)
                    </td>
                </tr>
            }
        </tbody>
    </table>

CourseWork/Views/Criminals/Archive.cshtml
@model CourseWork.Models.Criminal

@{
    ViewData["Title"] = "Архивировать";
}

<h1>Архивировать преступника</h1>

<h3>Вы уверены что хотите архивировать преступника?</h3>
<div>
    <h4>Criminal</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            Имя
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            Фамилия
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            Прозвище
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NickName)
        </dd>
        <dt class="col-sm-2">
            Возраст
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class="col-sm-2">
            Рост
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class="col-sm-2">
            День рождения
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            Место рождения
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthPlace)
        </dd>
        <dt class="col-sm-2">
            Пол
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sex)
        </dd>
        <dt class="col-sm-2">
            Цвет волос
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HairColor)
        </dd>
        <dt class="col-sm-2">
            Цвет глаз
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EyeColor)
        </dd>
        <dt class="col-sm-2">
            Особые приметы
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ExtraSigns)
        </dd>
        <dt class="col-sm-2">
            Последнее место жительства
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastAccomodation)
        </dd>
    </dl>

    <form asp-action="Archive">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Сохранить" class="btn btn-danger"/> |
        <a asp-action="Index">Вернуться </a>
    </form>
</div>

CourseWork/Views/Criminals/Archived.cshtml
@using Microsoft.EntityFrameworkCore.Internal
@model IEnumerable<CourseWork.Models.Criminal>

@{
    ViewData["Title"] = "Список Архивированых преступников";
}

<h1 class="text-center">Список архивированых преступников</h1>

@using (Html.BeginForm())
{
    <p>
        @Html.TextBox("SearchString")  
        <button type="submit" class="btn btn-primary">Искать</button>
    </p>
}
<table class="table col-auto">
    <thead>
        <tr>
            <th>ID</th>
            <th>
                Фамилия
            </th>
            <th>
                Имя
            </th>
            <th>
                Прозвище
            </th>
            <th>
                Возраст
            </th>
            <th>
                Рост
            </th>
            <th>
                Дата рождения
            </th>
            <th>
                Место рождения
            </th>
            <th>
                Пол
            </th>
            <th>
                Цвет волос
            </th>
            <th>
                Цвет глаз
            </th>
            <th>
                Особые приметы
            </th>
            <th>
                Последнее место жительства
            </th>
            <th>Организации</th>
            <th>Преступления</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.OrderBy(p=>p.LastName)) {
    @if (item.IsArchived)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NickName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthPlace)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sex)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HairColor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EyeColor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExtraSigns)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastAccomodation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrganisationsAsString)
                <a class="btn btn-success" asp-controller="Criminals" asp-action="AddOrganisation" asp-route-criminal_id="@item.Id">Добавить</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CrimesAsString)
                <a class="btn btn-success" asp-controller="Criminals" asp-action="AddCrime" asp-route-criminal_id="@item.Id">Добавить</a>
            </td>
            <td>
                <a class="btn btn-primary text-white col-12" asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                <a class="btn btn-primary text-white col-12" asp-action="Details" asp-route-id="@item.Id">Еще</a>
                <a class="btn btn-danger text-white col-12" asp-action="Archive" asp-route-id="@item.Id">Деархивировать</a>
                <a class="btn btn-danger text-white col-12" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>}
}
    </tbody>
</table>

CourseWork/Views/Criminals/Create.cshtml
@model CourseWork.Models.Criminal

@{
    ViewData["Title"] = "Создание записи";
}

<h1>Добавить нового преступника</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">Имя</label>
                <input asp-for="FirstName" class="form-control" type="text"/>
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Фамилия</label>
                <input asp-for="LastName" class="form-control" type="text"/>
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NickName" class="control-label">Прозвище</label>
                <input asp-for="NickName" class="form-control" type="text"/>
                <span asp-validation-for="NickName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label" >Возраст</label>
                <input asp-for="Age" class="form-control" type="number" placeholder="00" value="0"/>
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height" class="control-label">Рост</label>
                <input asp-for="Height" class="form-control" type="number" step="0.01"/>
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label" >Дата рождения</label>
                <input asp-for="BirthDate" class="form-control" type="datetime-local"/>
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthPlace" class="control-label" >Место рождения</label>
                <input asp-for="BirthPlace" class="form-control" type="text" />
                <span asp-validation-for="BirthPlace" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Пол</label>
                <select class="form-control" asp-for="Sex"> 
                        <option></option>
                        <option>Мужской</option>
                    <option>Женский</option>
                    </select>
            </div>
            <div class="form-group">
                <label asp-for="HairColor" class="control-label">Цвет волос</label>
                <input asp-for="HairColor" class="form-control"type="text" />
                <span asp-validation-for="HairColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EyeColor" class="control-label">Цвет глаз</label>
                <select asp-for="EyeColor" class="form-control" type="text">
                    <option></option>
                    <option>Голубые</option>
                    <option>Зеленые</option>
                    <option>Карие</option>
                    <option>Серые</option>
                </select>
                <span asp-validation-for="EyeColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExtraSigns" class="control-label">Особые преметы</label>
                <input asp-for="ExtraSigns" class="form-control" type="text"/>
                <span asp-validation-for="ExtraSigns" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastAccomodation" class="control-label">Последнее место жительства</label>
                <input asp-for="LastAccomodation" class="form-control" type="text"/>
                <span asp-validation-for="LastAccomodation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
                <a class="btn btn-danger" asp-action="Index">Вернуться</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CourseWork/Views/Criminals/Index.cshtml
@using Microsoft.EntityFrameworkCore.Internal
@model IEnumerable<CourseWork.Models.Criminal>

@{
    ViewData["Title"] = "Список преступников";
}

<h1 class="text-center">Список преступников</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Добавить преступника</a>
</p>

@using (Html.BeginForm())
{
    <p>
        @Html.TextBox("SearchString")  
        <button type="submit" class="btn btn-primary">Искать</button>
    </p>
}
<table class="table col-auto">
    <thead class="thead-light">
        <tr>
            <th>ID</th>
            <th>
                Фамилия
            </th>
            <th>
                Имя
            </th>
            <th>
                Прозвище
            </th>
            <th>
                Возраст
            </th>
            <th>
                Рост
            </th>
            <th>
                Дата рождения
            </th>
            <th>
                Место рождения
            </th>
            <th>
                Пол
            </th>
            <th>
                Цвет волос
            </th>
            <th>
                Цвет глаз
            </th>
            <th>
                Особые приметы
            </th>
            <th>
                Последнее место жительства
            </th>
            <th>Организации</th>
            <th>Преступления</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.OrderBy(p=>p.LastName)) {
    @if (!item.IsArchived)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NickName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthPlace)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sex)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HairColor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EyeColor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExtraSigns)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastAccomodation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrganisationsAsString)
                @if (User.Identity.IsAuthenticated)
                {<a class="btn btn-success" asp-controller="Criminals" asp-action="AddOrganisation" asp-route-criminal_id="@item.Id">Добавить</a>}
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CrimesAsString)
                @if (User.Identity.IsAuthenticated)
                {<a class="btn btn-success" asp-controller="Criminals" asp-action="AddCrime" asp-route-criminal_id="@item.Id">Добавить</a>}
            </td>
            <td>
                @if (User.Identity.IsAuthenticated)
                {
                <a class="btn btn-primary text-white col-12" asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                <a class="btn btn-primary text-white col-12" asp-action="Details" asp-route-id="@item.Id">Еще</a>
                <a class="btn btn-danger text-white col-12" asp-action="Archive" asp-route-id="@item.Id">Архивировать</a>
                <a class="btn btn-danger text-white col-12" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>}
            </td>
        </tr>}
}
    </tbody>
</table>